spring.application.name=habit_tracker_g146

spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.url=jdbc:postgresql://localhost:5433/postgres?currentSchema=g146
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
